### ISSUE TITLE
Off-topic question, but what theme are your using?

### ISSUE THREAD

**Issue by AJeezy9** [KunihikoKido/sublime-elasticsearch-client#1]
The screenshots of your ST interface looks beautiful.  Please share?

**Comment by KunihikoKido** [comment]
Hi, I am using itg.flat theme . :smile: 
- Theme - [itg.flat](https://packagecontrol.io/packages/Theme%20-%20itg.flat)
- Color Schme - [Colorsublime](https://packagecontrol.io/packages/Colorsublime)

``` json
{
    "theme": "itg.flat.dark.green.sublime-theme",
    "color_scheme": "Packages/Colorsublime - Themes/Solarized-light.tmTheme"
}
```

**Comment by AJeezy9** [comment]
Awesome. Thanks :)
